# Created by argbash-init v2.10.0
# ARG_POSITIONAL_SINGLE([MODE],[MODE = <deploy|send-keys>])
# ARG_POSITIONAL_SINGLE([CONFIG],[CONFIG = darwinConfigurations.\$CONFIG])
# ARG_OPTIONAL_SINGLE([target],[t],[specifies an ssh target if the default of \$CONFIG needs to be overridden])
# ARG_DEFAULTS_POS([])
# ARG_HELP([\ndarwin -- a helper script for darwinConfiguration deploys and key pushes\n])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='th'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_mode=
_arg_config=
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_target=


print_help()
{
	printf '%s\n' "
darwin -- a helper script for darwinConfiguration deploys and key pushes
"
	printf 'Usage: %s [-t|--target <arg>] [-h|--help] <MODE> <CONFIG>\n' "$0"
	printf '\t%s\n' "<MODE>: MODE = <deploy|send-keys>"
	printf '\t%s\n' "<CONFIG>: CONFIG = darwinConfigurations.\$CONFIG"
	printf '\t%s\n' "-t, --target: specifies an ssh target if the default of \$CONFIG needs to be overridden (no default)"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-t|--target)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_target="$2"
				shift
				;;
			--target=*)
				_arg_target="${_key##--target=}"
				;;
			-t*)
				_arg_target="${_key##-t}"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="'MODE' and 'CONFIG'"
	test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
	test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_mode _arg_config "

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
