{
 "title": "Mac Mini Zfs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(node_zfs_arc_c,alias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ARC Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_zfs_arc_size{alias=\"${host}\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "node_zfs_arc_c{alias=\"${host}\"}",
     "legendFormat": "Goal"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{alias=\"${host}\"} - node_memory_MemFree_bytes{alias=\"${host}\"} - node_memory_Buffers_bytes{alias=\"${host}\"} - node_memory_Cached_bytes{alias=\"${host}\"} - node_memory_Slab_bytes{alias=\"${host}\"} - node_memory_PageTables_bytes{alias=\"${host}\"} - node_memory_SwapCached_bytes{alias=\"${host}\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{alias=\"${host}\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{alias=\"${host}\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{alias=\"${host}\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{alias=\"${host}\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{alias=\"${host}\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{alias=\"${host}\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{alias=\"${host}\"} - node_memory_SwapFree_bytes{alias=\"${host}\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{alias=\"${host}\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "ARC Hit Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_zfs_arc_hits{alias=\"${host}\"} / (node_zfs_arc_hits{alias=\"${host}\"} + node_zfs_arc_misses{alias=\"${host}\"})",
     "legendFormat": "Hit Percentage"
    }
   ]
  }
 ]
}