{
 "title": "Spongix",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "60s",
 "panels": [
  {
   "title": "Index vs Chunk Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "prometheus_spongix_inflated_size_local",
     "legendFormat": "inflated"
    },
    {
     "expr": "prometheus_spongix_chunk_size_local",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Deduplication Efficiency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (prometheus_spongix_chunk_size_local / prometheus_spongix_inflated_size_local)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cache space left",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_spongix_max_size_local - prometheus_spongix_chunk_size_local",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Index Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_spongix_index_count_local",
     "legendFormat": "index"
    },
    {
     "expr": "prometheus_spongix_chunk_count_local",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Chunk GC Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "prometheus_spongix_chunk_gc_bytes_local",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Index Walk Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_spongix_index_walk_local[$__rate_interval:1h])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Chunk Walk Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_spongix_chunk_walk_local[$__rate_interval:1h])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_spongix_index_gc_count_local",
     "legendFormat": "index"
    },
    {
     "expr": "prometheus_spongix_chunk_gc_count_local",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_spongix_gc_time_local[$__rate_interval:1h])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Remote Cache Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_spongix_remote_cache_ok",
     "legendFormat": "ok"
    },
    {
     "expr": "prometheus_spongix_remote_cache_fail",
     "legendFormat": "fail"
    }
   ]
  },
  {
   "title": "Chunk Verify",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_spongix_verify_time_local[$__rate_interval:1h])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Chunk Directories",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_spongix_chunk_dir_count",
     "legendFormat": "dirs"
    }
   ]
  }
 ]
}