#ENC[AES256_GCM,data:baWvmD4S+qgXyhViXUnf,iv:p3tovvF6LHRECJxd0vlPVtosr7YwWTPEge5go5eAIGs=,tag:BDKNUJKVYMsJzxlFqdcaxQ==,type:comment]
#ENC[AES256_GCM,data:GVwarL0vKa6eOyroNQvRxDNkyssAZ1q1aUV6NFDj7Y4sUkmua+hdfQ+toaZajvc=,iv:6nhcefV1l2fW/NU3fDLAerTcgEB7joDnYlzZ+O2x134=,tag:OIzjkwBb1aSwKiyAbZK/hQ==,type:comment]
patroniApi: ENC[AES256_GCM,data:7N3X,iv:I4M1bj+dVRyr74UxGVVuph5Ad7eEEw9ghse+QE5mB1w=,tag:HeNZPJYz2whhz2Yv8dUTjw==,type:str]
patroniApiPass: ENC[AES256_GCM,data:v4+I6PqAqyq50Ru4oa/kNXgZjBvii75Vi3Sgk6tuaVo=,iv:+aziPUJtDuMy2/6TGQwktsGNgl37772K0EoR3jwnED0=,tag:hgLKNSMVfHEMo902XQ3gFA==,type:str]
patroniRepl: ENC[AES256_GCM,data:M2qz1A==,iv:YMaKN67oCw5mPPJvvASjzA/9CvhYRF0fSOL64E3dofw=,tag:FgNrW7NnUDvD5AKF6P3mEw==,type:str]
patroniReplPass: ENC[AES256_GCM,data:btzzPN5GGkrPi7fDKZ6qVSi3v8GKuZy/Ro49LKTJ7qg=,iv:e5bXzRqEYE+buUrYBt1CQfFCB18Hl3Nf/b97fTgnPBI=,tag:WHs+Z5LljEsG+99ea87Q9g==,type:str]
patroniRewind: ENC[AES256_GCM,data:t3PpF3E8,iv:yQ9iSwyJ06xV9bLKbhjeqQXjt57P/8w+8BEQP5JnyAo=,tag:+UbxIyq4YF3gwRwyQx6qGw==,type:str]
patroniRewindPass: ENC[AES256_GCM,data:oaFi9yErsUQyjxJRp2J2ag6Q4UmaeJhoVotGVMG7wvs=,iv:UgvPFrAqmpRwLqxelywavDSt9FNphpaSEitX8LxxbqY=,tag:jxGmpQ8nGwgMJVwlVrfw3A==,type:str]
patroniSuper: ENC[AES256_GCM,data:q2jS,iv:88Vbktys7jYJgxrDd9SwRkMNalbfAm7LjoSPxpm0/0k=,tag:2v+DmyfWnTPgUifRwRSeNg==,type:str]
patroniSuperPass: ENC[AES256_GCM,data:6//tfufKGHoS2k24ywTdc78yhZeC6ID15H8ezIZQSo0=,iv:8dkfnkLLMbfWZHd+QezgnK+L8LOxaHJIUCREUfAbOeA=,tag:dBLSYxnXQwBLlvWpnDYv8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://vault.ci.iog.io
          engine_path: sops
          key_name: ops
          created_at: "2022-04-22T16:31:48Z"
          enc: vault:v1:NKNt0+n8/ij6bjpHqxgMu+M4bsF+RasH1yzL2H7lBlnltXuQYFMPCvrfCsd/B+/LAw4Nc3N7sTHBlSlO
    age: []
    lastmodified: "2022-04-22T16:31:59Z"
    mac: ENC[AES256_GCM,data:TT06k2PUb4QgpEVo9l2vw8g8y8u9+YwedSLUamHSc6qaJtcdS2erld8HqR2Nq4yvOwjp3cfFvy/S6yX7xiTcTVRrcXFrXlqsiNXpjSocKiQ6UiDenFiS1M38rxNWkKne1Cku/2XOA8gNMVSM2VdONKgdlljfARsMQwZ7v6ItTK8=,iv:2mAxOn/bm4oKV9aZ4nrwjp8To3UfIC45tX2BeA8NQoY=,tag:Thq8uynyZm/kLeFRzUtg0g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
