project: SRE
custom-commands:
- name: ls-sre
  queryfields: labels
  help: jira ls on 'project = SRE and labels = ci-world'
  script: |
    jira ls -q 'resolution = unresolved AND project = SRE AND labels = ci-world ORDER BY priority ASC, created'
