project: CI
custom-commands:
- name: ls-sre
  help: jira ls on 'Delivering Team = Resident SRE'
  script: |
    jira ls -q 'resolution = unresolved AND "Delivering Team[Dropdown]" = "Resident SRE" AND project = CI ORDER BY priority ASC, created'
